Added support for download from HTTPS only
eclipse-leda/leda-contrib-self-update-agent pull request #37
Opened 2023-06-26 12:28 UTC by OleksandrChaika

2023-06-26 14:28 UTC, OlavHerbst requested changes
found some minors

2023-06-26 14:28 UTC, OlavHerbst commented on src/Download/Downloader.cpp
> +    sua::TechCode download(sua::Context & context, const char* url)
To give the whole context to a global function is too much, just the certificate filename would be sufficient.

2023-06-26 14:28 UTC, OlavHerbst commented on src/Download/Downloader.cpp
> +    sua::TechCode download(sua::Context & context, const char* url)
Decl. of download() and write_data() in line 40 are obsolete.
At least for download() the parameter list to be adapted.

2023-06-26 14:28 UTC, OlavHerbst commented on src/main.cpp
> +    std::string pathToCertificate{"/etc/ssl/certs/selfupdateagent.crt"};
Set the string as global const string to be used here and in Context init. - and in the help text.
Same for "/data/selfupdates" in line 60 and 49.
Perhaps a DEFINE would be sufficient to avoid string operations in help text.

2023-06-26 14:28 UTC, OlavHerbst commented on src/main.cpp
> +-c, --ca        path to certificate to verify connection with bundle server (default is '/etc/ssl/certs/selfupdateagent.crt')
line too long - max. 80 / 100 cols (like line 49) / 120?
If file paths will change their length in future better "(default is.." in separate lines?

2023-06-26 14:28 UTC, OlavHerbst commented on utest/TestSelfUpdateScenarios.cpp
> +       }
idention +1

2023-06-26 14:28 UTC, OlavHerbst commented on utest/sua-certificate.config
> +default_bits  = 2048
remove one space

2023-06-26 14:28 UTC, OlavHerbst commented on .github/actions/build-native-binary/action.yaml
> +        -out /etc/ssl/certs/selfupdateagent.crt \
Will these paths be overwritten by a system update or are they linked to another partition?

2023-06-26 14:28 UTC, OlavHerbst commented on src/Context.h
> +        std::string                             certificateFileName = "/etc/ssl/certs/selfupdateagent.crt";
Init updatesDirectory and certificateFileName better with a global const string/DEFINE, ref. main()

2023-06-26 14:34 UTC, OlavHerbst requested changes
minor findings

2023-06-26 14:34 UTC, OlavHerbst commented on utest/sua-certificate.config
> +countryName = XX
better also "N/A" ?

2023-06-26 19:32 UTC, OleksandrChaika commented on src/Download/Downloader.cpp
> +    sua::TechCode download(sua::Context & context, const char* url)
Fixed

2023-06-26 19:32 UTC, OleksandrChaika commented on src/Download/Downloader.cpp
> +    sua::TechCode download(sua::Context & context, const char* url)
Obsolete lines removed.

2023-06-26 19:32 UTC, OleksandrChaika commented on src/main.cpp
> +-c, --ca        path to certificate to verify connection with bundle server (default is '/etc/ssl/certs/selfupdateagent.crt')
Fixed, all defaults are on new line.

2023-06-26 19:32 UTC, OleksandrChaika commented on utest/TestSelfUpdateScenarios.cpp
> +       }
Fixed

2023-06-26 19:32 UTC, OleksandrChaika commented on utest/sua-certificate.config
> +default_bits  = 2048
Fixed

2023-06-26 19:33 UTC, OleksandrChaika commented on .github/actions/build-native-binary/action.yaml
> +        -out /etc/ssl/certs/selfupdateagent.crt \
These 2 files are only for workflow run. Self-update-agent will receive certificates from system image each time.

2023-06-26 19:33 UTC, OleksandrChaika commented on utest/sua-certificate.config
> +countryName = XX
Fixed

2023-06-27 08:16 UTC, OlavHerbst approved these changes
The fixes are ok.

2023-06-27 08:57 UTC, merged