Preserve internal state if disconnected from MQTT Broker
eclipse-leda/leda-contrib-self-update-agent pull request #41
Opened 2023-07-12 09:28 UTC by OleksandrChaika

2023-07-12 11:00 UTC, OlavHerbst requested changes
error in error message

2023-07-12 11:00 UTC, OlavHerbst commented on src/Mqtt/MqttProcessor.cpp
>                      ctx.stateMachine->handleEvent(c.event);
If all handled exceptions occur in this statement, then move the try-catch-block to here.

2023-07-12 11:00 UTC, OlavHerbst commented on src/Mqtt/MqttProcessor.cpp
> +                sua::Logger::error("Incomplete desired state request, unable to identify: '{}'", e.what());
mention "json" in error message

2023-07-12 11:00 UTC, OlavHerbst commented on src/Mqtt/MqttProcessor.cpp
> +                sua::Logger::error("Malformed desired state request, unable to identify: '{}'", topic, e.what());
remove topic

2023-07-12 11:00 UTC, OlavHerbst commented on src/Mqtt/MqttProcessor.cpp
>                  ctx.desiredState.activityId = nlohmann::json::parse(message).at("activityId");
Why is activityId extracted if runtime_error or json::exception, but not at the other exceptions? Missing a comment.

2023-07-13 06:20 UTC, OleksandrChaika commented on src/Mqtt/MqttProcessor.cpp
>                      ctx.stateMachine->handleEvent(c.event);
Not only here, also in ->read... call to protocol parser.

2023-07-13 06:20 UTC, OleksandrChaika commented on src/Mqtt/MqttProcessor.cpp
> +                sua::Logger::error("Incomplete desired state request, unable to identify: '{}'", e.what());
JSON added to the message

2023-07-13 06:20 UTC, OleksandrChaika commented on src/Mqtt/MqttProcessor.cpp
> +                sua::Logger::error("Malformed desired state request, unable to identify: '{}'", topic, e.what());
Removed

2023-07-13 06:21 UTC, OleksandrChaika commented on src/Mqtt/MqttProcessor.cpp
>                  ctx.desiredState.activityId = nlohmann::json::parse(message).at("activityId");
Comments added. But exception handling can be improved definitely. I think we could parse request as it is and then do a consistency check after that.

2023-07-13 07:54 UTC, OlavHerbst approved these changes
ok

2023-07-13 08:00 UTC, OlavHerbst commented on src/Mqtt/MqttProcessor.cpp
>                  ctx.desiredState.activityId = nlohmann::json::parse(message).at("activityId");
ok

2023-07-13 08:08 UTC, merged